export enum UserRole {
  INVESTOR = 'INVESTOR',
  ENTREPRENEUR = 'ENTREPRENEUR',
  ASSESSOR = 'ASSESSOR',
  ADMIN = 'ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  BLOCKED = 'BLOCKED',
}

export enum KycStatus {
  NOT_STARTED = 'NOT_STARTED',
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum ProjectStatus {
  DRAFT = 'DRAFT',
  UNDER_REVIEW = 'UNDER_REVIEW',
  ACTIVE = 'ACTIVE',
  FUNDED = 'FUNDED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ProjectSector {
  SOLAR = 'SOLAR',
  WIND = 'WIND',
  HYDRO = 'HYDRO',
  BIOMASS = 'BIOMASS',
  EV_CHARGING = 'EV_CHARGING',
  GREEN_HYDROGEN = 'GREEN_HYDROGEN',
  ENERGY_STORAGE = 'ENERGY_STORAGE',
  OTHER = 'OTHER',
}

export enum ProjectStage {
  CONCEPT = 'CONCEPT',
  FEASIBILITY = 'FEASIBILITY',
  CONSTRUCTION = 'CONSTRUCTION',
  OPERATIONAL = 'OPERATIONAL',
  EXPANSION = 'EXPANSION',
}

export enum MilestoneStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  OVERDUE = 'OVERDUE',
}

export enum InvestmentStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum TransactionType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  INVESTMENT = 'INVESTMENT',
  RETURN = 'RETURN',
  FEE = 'FEE',
  REFUND = 'REFUND',
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethod {
  BANK_TRANSFER = 'BANK_TRANSFER',
  CARD = 'CARD',
  CRYPTO = 'CRYPTO',
  MOBILE_MONEY = 'MOBILE_MONEY',
}

export enum DueDiligenceStatus {
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  UNDER_REVIEW = 'UNDER_REVIEW',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
}

export enum ComplianceAlertType {
  KYC_ISSUE = 'KYC_ISSUE',
  AML_FLAG = 'AML_FLAG',
  DOCUMENT_EXPIRY = 'DOCUMENT_EXPIRY',
  REGULATORY_CHANGE = 'REGULATORY_CHANGE',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
}

export enum ComplianceAlertSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum ComplianceAlertStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED',
}

export enum DisputeType {
  PAYMENT = 'PAYMENT',
  PROJECT_DELIVERY = 'PROJECT_DELIVERY',
  FRAUD = 'FRAUD',
  COMMUNICATION = 'COMMUNICATION',
  OTHER = 'OTHER',
}

export enum DisputeStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  MEDIATION = 'MEDIATION',
  RESOLVED = 'RESOLVED',
  ESCALATED = 'ESCALATED',
  CLOSED = 'CLOSED',
}

export enum NotificationType {
  PROJECT_UPDATE = 'PROJECT_UPDATE',
  INVESTMENT_UPDATE = 'INVESTMENT_UPDATE',
  DUE_DILIGENCE = 'DUE_DILIGENCE',
  COMPLIANCE = 'COMPLIANCE',
  MESSAGE = 'MESSAGE',
  SYSTEM = 'SYSTEM',
}

export enum AssessorType {
  INDIVIDUAL_CONSULTANT = 'INDIVIDUAL_CONSULTANT',
  FIRM = 'FIRM',
  NGO = 'NGO',
  GOVERNMENT_BODY = 'GOVERNMENT_BODY',
  ACADEMIC = 'ACADEMIC',
}

export enum AssessorAvailability {
  AVAILABLE = 'AVAILABLE',
  BUSY = 'BUSY',
  ON_LEAVE = 'ON_LEAVE',
}

export enum InvestorType {
  INDIVIDUAL = 'INDIVIDUAL',
  INSTITUTIONAL = 'INSTITUTIONAL',
  IMPACT_FUND = 'IMPACT_FUND',
  CORPORATE = 'CORPORATE',
}

export enum RiskTolerance {
  CONSERVATIVE = 'CONSERVATIVE',
  MODERATE = 'MODERATE',
  AGGRESSIVE = 'AGGRESSIVE',
}

export enum EntrepreneurStage {
  IDEA = 'IDEA',
  MVP = 'MVP',
  EARLY_REVENUE = 'EARLY_REVENUE',
  GROWTH = 'GROWTH',
  SCALE = 'SCALE',
}
